- name: PLAY1
  hosts: prod
  tasks:
    - copy: 
        src: /home/devops/prodinv
        dest: /tmp
    - file:
        path: /tmp/devops.txt
        state: touch
- name: PLAY2
  hosts: qa
  tasks:
    - copy:
        src: /etc/resolv.conf
        dest: /tmp
    - file: 
        path: /tmp/hello
        state: directory
